/* 
 * Robot vacuum cleaner
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FeedbackApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class FeedbackApiTests
    {
        private FeedbackApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new FeedbackApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FeedbackApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' FeedbackApi
            //Assert.IsInstanceOfType(typeof(FeedbackApi), instance, "instance is a FeedbackApi");
        }

        /// <summary>
        /// Test GetFeedback
        /// </summary>
        [Test]
        public void GetFeedbackTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetFeedback();
            //Assert.IsInstanceOf<Feedback> (response, "response is Feedback");
        }
        /// <summary>
        /// Test SendFeedback
        /// </summary>
        [Test]
        public void SendFeedbackTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Feedback body = null;
            //instance.SendFeedback(body);
            
        }
    }

}
