/* 
 * Robot vacuum cleaner
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RoomApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class RoomApiTests
    {
        private RoomApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new RoomApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RoomApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' RoomApi
            //Assert.IsInstanceOfType(typeof(RoomApi), instance, "instance is a RoomApi");
        }

        /// <summary>
        /// Test CreateRoom
        /// </summary>
        [Test]
        public void CreateRoomTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Room body = null;
            //instance.CreateRoom(body);
            
        }
        /// <summary>
        /// Test DeleteRoomById
        /// </summary>
        [Test]
        public void DeleteRoomByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string roomId = null;
            //instance.DeleteRoomById(roomId);
            
        }
        /// <summary>
        /// Test GetRoom
        /// </summary>
        [Test]
        public void GetRoomTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetRoom();
            //Assert.IsInstanceOf<Room> (response, "response is Room");
        }
        /// <summary>
        /// Test GetRoomById
        /// </summary>
        [Test]
        public void GetRoomByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? roomId = null;
            //var response = instance.GetRoomById(roomId);
            //Assert.IsInstanceOf<Room> (response, "response is Room");
        }
        /// <summary>
        /// Test UpdateRoom
        /// </summary>
        [Test]
        public void UpdateRoomTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Room body = null;
            //string roomId = null;
            //instance.UpdateRoom(body, roomId);
            
        }
    }

}
