/* 
 * Robot vacuum cleaner
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ScheduleApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ScheduleApiTests
    {
        private ScheduleApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ScheduleApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ScheduleApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ScheduleApi
            //Assert.IsInstanceOfType(typeof(ScheduleApi), instance, "instance is a ScheduleApi");
        }

        /// <summary>
        /// Test CreateTaskInSchedule
        /// </summary>
        [Test]
        public void CreateTaskInScheduleTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //TaskForRobot body = null;
            //instance.CreateTaskInSchedule(body);
            
        }
        /// <summary>
        /// Test CreateTaskInSchedule1
        /// </summary>
        [Test]
        public void CreateTaskInSchedule1Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string taskId = null;
            //TaskForRobot body = null;
            //instance.CreateTaskInSchedule1(taskId, body);
            
        }
        /// <summary>
        /// Test GetScheduleAllRobots
        /// </summary>
        [Test]
        public void GetScheduleAllRobotsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetScheduleAllRobots();
            //Assert.IsInstanceOf<TaskForRobot> (response, "response is TaskForRobot");
        }
        /// <summary>
        /// Test GetScheduleByIdRobots
        /// </summary>
        [Test]
        public void GetScheduleByIdRobotsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? idRobot = null;
            //var response = instance.GetScheduleByIdRobots(idRobot);
            //Assert.IsInstanceOf<TaskForRobot> (response, "response is TaskForRobot");
        }
        /// <summary>
        /// Test UpdateTaskInSchedule
        /// </summary>
        [Test]
        public void UpdateTaskInScheduleTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //TaskForRobot body = null;
            //string scheduleId = null;
            //instance.UpdateTaskInSchedule(body, scheduleId);
            
        }
    }

}
