/* 
 * Robot vacuum cleaner
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// StatisticWork
    /// </summary>
    [DataContract]
        public partial class StatisticWork :  IEquatable<StatisticWork>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StatisticWork" /> class.
        /// </summary>
        /// <param name="staticInformation">staticInformation.</param>
        public StatisticWork(string staticInformation = default(string))
        {
            this.StaticInformation = staticInformation;
        }
        
        /// <summary>
        /// Gets or Sets StaticInformation
        /// </summary>
        [DataMember(Name="staticInformation", EmitDefaultValue=false)]
        public string StaticInformation { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class StatisticWork {\n");
            sb.Append("  StaticInformation: ").Append(StaticInformation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as StatisticWork);
        }

        /// <summary>
        /// Returns true if StatisticWork instances are equal
        /// </summary>
        /// <param name="input">Instance of StatisticWork to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StatisticWork input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.StaticInformation == input.StaticInformation ||
                    (this.StaticInformation != null &&
                    this.StaticInformation.Equals(input.StaticInformation))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.StaticInformation != null)
                    hashCode = hashCode * 59 + this.StaticInformation.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
