/* 
 * Robot vacuum cleaner
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TaskForRobotOnlyLaunch
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TaskForRobotOnlyLaunchTests
    {
        // TODO uncomment below to declare an instance variable for TaskForRobotOnlyLaunch
        //private TaskForRobotOnlyLaunch instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TaskForRobotOnlyLaunch
            //instance = new TaskForRobotOnlyLaunch();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TaskForRobotOnlyLaunch
        /// </summary>
        [Test]
        public void TaskForRobotOnlyLaunchInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TaskForRobotOnlyLaunch
            //Assert.IsInstanceOfType<TaskForRobotOnlyLaunch> (instance, "variable 'instance' is a TaskForRobotOnlyLaunch");
        }


        /// <summary>
        /// Test the property 'RobotId'
        /// </summary>
        [Test]
        public void RobotIdTest()
        {
            // TODO unit test for the property 'RobotId'
        }
        /// <summary>
        /// Test the property 'RoomId'
        /// </summary>
        [Test]
        public void RoomIdTest()
        {
            // TODO unit test for the property 'RoomId'
        }
        /// <summary>
        /// Test the property 'CleaningMode'
        /// </summary>
        [Test]
        public void CleaningModeTest()
        {
            // TODO unit test for the property 'CleaningMode'
        }

    }

}
